apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildpacks-creator
spec:
  description: >-
    Build and push an image using the Paketo Buildpacks lifecycle 'creator' directly.
    This task is a more manual approach compared to using 'pack', but allows for finer control
    over the build process and can be more efficient in certain CI/CD environments.
  params:
    - name: image
      type: string
      description: Container image reference to build and push
    - name: builder_image
      type: string
      default: paketobuildpacks/builder-jammy-full:0.3.622@sha256:25efe93f3afa866e058f1bf6f72b5734dbd270a4b60e344a0df2d613bc19074c
      description: Container image reference for the builder that contains the lifecycle and buildpacks.
    - name: component_path
      type: string
      default: "."
      description: Subdirectory within the workspace where the application resides.
  workspaces:
    - name: source
      description: Workspace with the source code.
    - name: docker-config
      description: Non-optional workspace with the config.json for registry authentication.
    - name: cache
      description: Persistent volume for build caches.
      optional: true
  steps:
    - name: build-and-push
      image: $(params.builder_image)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsUser: 0
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        # 1. If the workspace with Docker config is provided, set up the DOCKER_CONFIG environment variable
        if [ -d "$(workspaces.docker-config.path)" ]; then
          export DOCKER_CONFIG="/tekton/home/.docker"
          mkdir -p "$DOCKER_CONFIG"
          cp "$(workspaces.docker-config.path)/.dockerconfigjson" "$DOCKER_CONFIG/config.json"
        fi

        # 2. Determinate the application path based on the component_path parameter
        app_path="$(workspaces.source.path)/$(params.component_path)"
        chmod -R 777 "$(workspaces.source.path)"
        
        # 3.  Create layers directory for the build output
        layers_dir="/layers"
        mkdir -p "$layers_dir"

        # 4. Configure cache flags if cache workspace is bound
        cache_flags=""
        if [ "$(workspaces.cache.bound)" == "true" ]; then
          cache_flags="-cache-dir=$(workspaces.cache.path)"
        fi

        echo "-----> Initializing 'creator'..."
        export CNB_PLATFORM_API=0.10
        /cnb/lifecycle/creator \
          -app="$app_path" \
          -layers="$layers_dir" \
          $cache_flags \
          -report="$layers_dir/report.toml" \
          "$(params.image)"