apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
resources:
  - tasks/git-clone.yaml
  - tasks/pack-build-push.yaml
  - tasks/kubectl-patch.yaml
  - tasks/notify.yaml
  - tasks/detect-and-dispatch.yaml
  - pipelines/build-deploy-component.yaml
  - pipelines/dispatcher.yaml
  - triggers/triggerbinding.yaml
  - triggers/triggertemplate-dispatcher.yaml
  - triggers/eventlistener.yaml
