apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cicd-listener
  namespace: cicd
  labels:
    app.kubernetes.io/part-of: saritasa-cicd
spec:
  serviceAccountName: dispatcher-sa
  triggers:
    - name: github-push
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
          params:
            - name: secretRef
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: eventTypes
              value: ["push"]
        - ref:
            name: cel
            kind: ClusterInterceptor
          params:
            - name: filter
              value: "body.ref.startsWith('refs/heads/')"
            - name: overlays
              value:
                - key: changed_files_json
                  expression: |
                    '[' + body.commits.map(c, c.added + c.modified + c.removed).flatten().map(f, '"'+string(f)+'"').join(',') + ']'
      bindings:
        - ref: github-push-binding
      template:
        ref: dispatcher-template
