apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: cicd
  labels:
    app.kubernetes.io/part-of: saritasa-cicd
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)
    - name: changed-files
      value: $(extensions.changed_files_json)
