apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-tekton-resources
  namespace: saritasa-devops-project
spec:
  description: A task to create Tekton resources to support running pipelines to build and deploy components.

  workspaces:
    - name: source
  
  steps:
    - name: create-resources
      image: alpine/k8s:1.33.13
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -eu

        TEKTON_RESOURCES_DIR=(".tekton/tasks" ".tekton/pipelines")

        for dir in "${TEKTON_RESOURCES_DIR[@]}"; do
            echo ""
            echo "Creating resources in $dir..."
            find "$dir" -type f | while read -r file; do
                echo "$file"
                kubectl apply -f $file
            done
        done
