apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton
  labels:
    app.kubernetes.io/part-of: saritasa-cicd
spec:
  serviceAccountName: el-github-listener-sa
  resources:
    kubernetesResource:
      serviceType: ClusterIP
  triggers:
    - triggerRef: github-webhook
