apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: old_sha
      value: $(body.before)
    - name: new_sha
      value: $(body.after)
    - name: git_url
      value: $(body.repository.clone_url)
    - name: image_prefix
      value: "docker.io/lbcristaldo"   
    - name: max_concurrent
      value: "5"      
    - name: pipeline_namespace
      value: "tekton-pipelines"