apiVersion: v1
kind: ResourceQuota
metadata:
  name: pipeline-quota
  namespace: tekton
  labels:
    app.kubernetes.io/part-of: saritasa-cicd
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "6Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pipeline-limits
  namespace: tekton
  labels:
    app.kubernetes.io/part-of: saritasa-cicd
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "500m"
        memory: "512Mi"
      default:
        cpu: "1"
        memory: "1Gi"
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "10m"
        memory: "32Mi"
