apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: saritasa-devops-build-samples
  namespace: tekton
  labels:
    app.kubernetes.io/part-of: saritasa-cicd
spec:
  url: "https://github.com/dknhat2000/saritasa-devops-build-samples"
  concurrency_limit: 2
