apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repository-source-pvc
  namespace: saritasa-devops-project 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi