apiVersion: v1
kind: LimitRange
metadata:
  name: cicd-limits
  namespace: cicd
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      max:
        cpu: "4"
        memory: 4Gi
