apiVersion: v1
kind: ResourceQuota
metadata:
  name: cicd-quota
  namespace: cicd
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
